version: '3'

services:
  nans-authentication-library-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nans-authentication-library-app
    tty: true 
    volumes:
      - .:/var/www/html
